// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euvxuuwhlirdnosdnbbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1dnh1dXdobGlyZG5vc2RuYmJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1ODgxMDIsImV4cCI6MjA3NzE2NDEwMn0.BLmjhGxk8Ze6PvQIZc4D7KHt774mUqR7XpI5FR5J3Rc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});